import test from 'node:test';
import assert from 'node:assert/strict';
import {ControllerInput} from '../dist/js/gamepad.js';
import {emptyInput} from '../dist/js/engine.js';
const pad=()=>({index:2,id:'DualSense Wireless Controller',mapping:'standard',connected:true,axes:[0,0,0,0],buttons:Array.from({length:17},()=>({pressed:false,value:0}))});
function fixture(){const p=pad(),c=new ControllerInput({});c.poll(()=>[null,null,p]);return {p,c,read(dt=1/60,context=false){c.poll(()=>[null,null,p]);const f=emptyInput();c.apply(f,dt,1,context);return f;}};}
test('DualSense maps triggers, sticks and every gameplay action',()=>{const{p,read}=fixture();p.axes=[.6,-.8,1,-1];for(const i of [0,1,2,3,4,5,6,7,10])p.buttons[i].pressed=true;const f=read();for(const k of ['jump','crouch','reload','swap','grenade','melee','ads','fire','firePressed','sprint'])assert.equal(f[k],true,k);assert(f.mx>0&&f.mz>0&&f.lx>0&&f.ly>0);const held=read();assert.equal(held.jump,false);assert.equal(held.fire,true);assert.equal(held.firePressed,false);});
test('Square interacts without reloading at an objective',()=>{const{p,read}=fixture();p.buttons[2].pressed=true;const f=read(1/60,true);assert.equal(f.interact,true);assert.equal(f.reload,false);});
test('neutral rearming prevents held shots and movement on resume and reconnect',()=>{const{p,c,read}=fixture();p.buttons[7].pressed=true;p.axes[0]=1;c.suspend();let f=read();assert.equal(f.fire,false);assert.equal(f.mx,0);p.buttons[7].pressed=false;p.axes[0]=0;read();p.buttons[7].pressed=true;assert.equal(read().fire,true);c.poll(()=>[]);assert.equal(c.lost,true);f=read();assert.equal(f.fire,false);});
test('radial dead zone eliminates drift and analog triggers fire',()=>{const{p,read}=fixture();p.axes=[.03,.02,.02,.03];p.buttons[7].value=.2;const f=read();assert.equal(f.mx,0);assert.equal(f.lx,0);assert.equal(f.fire,true);});
test('polling exceptions and unsupported mappings leave input neutral',()=>{const c=new ControllerInput({});c.poll(()=>{throw Error('blocked');});assert.equal(c.connected,false);const p=pad();p.mapping='';c.poll(()=>[p]);assert.equal(c.connected,false);});
test('Options edges survive suspend, and release allows a new press',()=>{const{p,c}=fixture();p.buttons[9].pressed=true;c.poll(()=>[p]);assert.equal(c.edges[9],1);c.suspend();c.poll(()=>[p]);assert.equal(c.edges[9],0);p.buttons[9].pressed=false;c.poll(()=>[p]);p.buttons[9].pressed=true;c.poll(()=>[p]);assert.equal(c.edges[9],1);});
test('look is frame-rate independent with ADS reduction and inverted Y',()=>{const{p,c,read}=fixture();p.axes[2]=1;p.axes[3]=.5;const a=read(1/60),b=read(1/30);assert(Math.abs(b.lx-2*a.lx)<1e-6);p.buttons[6].pressed=true;const ads=read();assert(ads.lx<a.lx);c.settings.controllerInvertY=true;assert(read().ly>0);});
