import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,emptyInput} from '../dist/js/engine.js';
import {Weapon,WEAPONS,GUN_ORDER} from '../dist/js/weapons.js';
import {Arena} from '../dist/js/maps.js';
import {Navigation} from '../dist/js/navigation.js';
import {rayBox,direction} from '../dist/js/math.js';

function duel(mode='tdm'){
 const g=new Game({mode},{seed:891});g.arena.blocks=[{x:0,y:-.2,z:0,w:200,h:.4,d:200,ground:true,surface:'concrete'}];
 g.actors=g.actors.filter(a=>a.id===0||a.id===4);const p=g.player,t=g.actors[1];p.reset({x:0,y:0,z:0},0);t.reset({x:0,y:0,z:-8},Math.PI);p.spawnProtection=t.spawnProtection=0;t.aiClock=10000;t.path=[];t.health=100;p.pitch=-.06;return{g,p,t};
}
function advance(g,seconds,input=emptyInput()){for(let t=0;t<seconds;t+=1/60)g.update(1/60,input);}

test('arsenal contains every requested category with unique timing and names',()=>{assert.equal(WEAPONS.length,13);assert.equal(new Set(WEAPONS.map(w=>w.name)).size,13);for(const kind of ['RIFLE','SMG','SHOTGUN','SNIPER','MARKSMAN','LMG','PISTOL','MELEE'])assert(WEAPONS.some(w=>w.kind===kind));assert.equal(GUN_ORDER.at(-1),12);});
test('ray intersection handles parallel, inside, missed and range-limited rays',()=>{const b={x:0,y:1,z:-4,w:2,h:2,d:2};assert.equal(rayBox({x:0,y:1,z:0},direction(0),b),3);assert.equal(rayBox({x:0,y:1,z:-4},direction(0),b),0);assert.equal(rayBox({x:4,y:1,z:0},direction(0),b),null);assert.equal(rayBox({x:0,y:1,z:0},direction(0),b,2),null);});
test('shots consume ammunition, obey fire rate and cause actual damage',()=>{const{g,p,t}=duel();assert(g.shoot(p));assert.equal(p.weapon.ammo,29);assert(t.health<100);assert(!g.shoot(p));assert.equal(p.weapon.ammo,29);assert(p.pitch>-.06);});
test('headshots deal more damage than body and limbs',()=>{const w=new Weapon(0);assert(w.damage(5,'head')>w.damage(5,'body'));assert(w.damage(5,'body')>w.damage(5,'leg'));assert(w.damage(90)<w.damage(5));});
test('hard cover stops bullets',()=>{const{g,p,t}=duel();g.arena.blocks.push({x:0,y:1,z:-4,w:3,h:3,d:1,surface:'concrete'});g.shoot(p);assert.equal(t.health,100);});
test('team combat has friendly fire disabled and FFA has no allies',()=>{const{g,p,t}=duel();t.team=0;g.shoot(p);assert.equal(t.health,100);const f=duel('ffa');f.t.team=0;f.g.shoot(f.p);assert(f.t.health<100);});
test('reload conserves ammunition and uses available reserves',()=>{const w=new Weapon(0);w.ammo=7;w.reserve=12;assert(w.reload());for(let i=0;i<150;i++)w.update(1/60);assert.equal(w.ammo,19);assert.equal(w.reserve,0);assert(!w.reload());});
test('pump shotgun reload adds individual shells and can be interrupted',()=>{const{g,p}=duel();p.weapons[0]=new Weapon(5);p.weapon.ammo=0;p.weapon.reload();for(let i=0;i<33;i++)p.weapon.update(1/60);assert.equal(p.weapon.ammo,1);assert(p.weapon.reloadLeft>0);assert(g.shoot(p));assert.equal(p.weapon.ammo,0);assert.equal(p.weapon.reloadLeft,0);});
test('attachments modify actual recoil, magazine size, ADS and range',()=>{const plain=new Weapon(0),comp=new Weapon(0,{barrel:2}),ext=new Weapon(0,{handling:4}),stock=new Weapon(0,{handling:3}),supp=new Weapon(0,{barrel:1});assert(comp.recoil<plain.recoil);assert(ext.capacity>plain.capacity);assert(ext.reloadTime>plain.reloadTime);assert(stock.adsTime<plain.adsTime);assert(supp.range<plain.range);});
test('walking, sprinting, crouching and jumping work without keyboard input',()=>{const{g,p}=duel();const input=emptyInput();input.mz=1;advance(g,.5,input);assert(p.z<-1);const walk=p.z;input.sprint=true;advance(g,.5,input);assert(walk-p.z>2.3);g.update(1/60,{...emptyInput(),crouch:true});assert(p.crouched);g.update(1/60,{...emptyInput(),crouch:true,jump:true});advance(g,.15);assert(p.y>.4);});
test('movement cannot tunnel through walls and can step up short stairs',()=>{const{g,p}=duel();g.arena.blocks.push({x:0,y:1.5,z:-3,w:8,h:3,d:1,surface:'concrete'});advance(g,2,{...emptyInput(),mz:1,sprint:true});assert(p.z>-2.3);const d=duel();d.g.arena.blocks.push({x:0,y:.15,z:-1.3,w:2,h:.3,d:1,surface:'concrete'});advance(d.g,.35,{...emptyInput(),mz:1});assert(d.p.y>.25);});
test('ADS, swap, reload and equipment respond to input actions',()=>{const{g,p}=duel();advance(g,.4,{...emptyInput(),ads:true});assert(p.ads>.9);g.update(1/60,{...emptyInput(),swap:true});assert.equal(p.slot,1);advance(g,.4);p.weapon.ammo=0;g.update(1/60,{...emptyInput(),reload:true});assert(p.weapon.reloadLeft>0);g.update(1/60,{...emptyInput(),grenade:true});assert.equal(g.grenades.length,1);assert.equal(p.grenades,1);});
test('frag damage falls off and respects cover',()=>{const{g,p,t}=duel();g.explode({x:0,y:1,z:-7,owner:p.id,kind:'frag'});assert(t.dead);const d=duel();d.g.arena.blocks.push({x:0,y:1.5,z:-6,w:8,h:3,d:1,surface:'concrete'});d.g.explode({x:0,y:1,z:-4,owner:0,kind:'frag'});assert.equal(d.t.health,100);});
test('smoke blocks sight and expires; flash affects visible combatants',()=>{const{g,p,t}=duel();assert(g.canSee(p,t));g.explode({x:0,y:1,z:-4,owner:0,kind:'smoke'});g.smokes[0].age=2;assert(!g.canSee(p,t));g.updateEquipment(17);assert.equal(g.smokes.length,0);g.explode({x:0,y:1.4,z:-2,owner:0,kind:'flash'});assert(p.flashed>0);});
test('death, respawn and spawn protection form a complete loop',()=>{const{g,p,t}=duel();g.damage(p,120,t);assert(p.dead);assert.equal(p.deaths,1);advance(g,3.1);assert(!p.dead);assert(p.spawnProtection>0);g.damage(p,100,t);assert.equal(p.health,100);});
test('paused and finished simulations cannot consume ammunition or time',()=>{const{g,p}=duel();g.paused=true;g.update(1/60,{...emptyInput(),fire:true});assert.equal(g.time,0);assert.equal(p.weapon.ammo,30);assert(!g.shoot(p));g.paused=false;g.rules.finish(0);g.update(1/60);assert.equal(g.time,0);});
test('TDM and FFA end at their score limits',()=>{for(const mode of ['tdm','ffa']){const{g,p,t}=duel(mode);for(let i=0;i<g.rules.mode.limit;i++){t.health=100;t.spawnProtection=0;g.damage(t,200,p);}assert.equal(g.rules.phase,'finished');assert.equal(g.rules.winner,0);}});
test('Gun Game advances through every weapon and finishes on a melee kill',()=>{const{g,p,t}=duel('gun');for(let i=0;i<12;i++){t.health=100;t.spawnProtection=0;g.damage(t,200,p);assert.equal(p.weapon.def.id,GUN_ORDER[i+1]);}t.health=100;t.x=0;t.y=0;t.z=-1.2;p.yaw=0;p.pitch=0;p.knifeCooldown=0;assert(g.melee(p));assert.equal(p.gunStage,13);assert.equal(g.rules.phase,'finished');});
test('domination captures, contests, awards points and finishes',()=>{const{g,p,t}=duel('domination'),q=g.rules.points[0];p.x=q.x;p.z=q.z;t.x=50;t.z=50;for(let i=0;i<310;i++)g.rules.update(1/60,g);assert.equal(q.owner,0);g.rules.scores[0]=149;g.rules.tick=.99;g.rules.update(.03,g);assert.equal(g.rules.phase,'finished');const d=duel('domination'),c=d.g.rules.points[0];d.p.x=d.t.x=c.x;d.p.z=d.t.z=c.z;d.g.rules.update(1,d.g);assert(c.contested);assert.equal(c.progress,0);});
test('sabotage can plant, defuse, switch teams and start another round',()=>{const{g,p,t}=duel('sabotage'),site=g.rules.points[0];p.x=site.x;p.z=site.z;p.interacting=true;t.x=20;t.z=20;for(let i=0;i<190;i++)g.rules.update(1/60,g);assert(g.rules.planted);assert.equal(g.rules.bombSite,0);p.interacting=false;t.x=site.x;t.z=site.z;t.interacting=true;for(let i=0;i<310;i++)g.rules.update(1/60,g);assert.equal(g.rules.phase,'roundBreak');assert.equal(g.rules.scores[1],1);g.rules.round=3;g.rules.nextRound();assert.equal(g.rules.attackingTeam,1);assert(!g.rules.planted);});
test('a planted charge remains live when all attackers die',()=>{const{g,p,t}=duel('sabotage');g.rules.planted=true;g.rules.bombSite=0;g.rules.bombTime=.05;p.health=0;g.rules.update(.02,g);assert.equal(g.rules.phase,'playing');g.rules.update(.04,g);assert.equal(g.rules.scores[0],1);});
test('sabotage disables mid-round respawning',()=>{const{g,p,t}=duel('sabotage');g.actors.push(Object.assign(Object.create(Object.getPrototypeOf(t)),t,{id:1,team:0,x:15,z:15,health:100,aiClock:1000}));g.damage(p,200,t);advance(g,4);assert(p.dead);});
test('every map has safe spawns and navigable routes to the objectives',()=>{for(let id=0;id<4;id++){const arena=new Arena(id),nav=new Navigation(arena);for(const spawn of arena.spawns)assert(!arena.collides(spawn,.31,1.75),`map ${id} invalid spawn`);for(const objective of arena.objectives){const path=nav.path(arena.spawns[0],objective);assert(path.length>0,`map ${id} no path`);assert(distance2(path.at(-1),objective)<4.5,`map ${id} ${objective.name} unreachable`);}}});
function distance2(a,b){return Math.hypot(a.x-b.x,a.z-b.z);}
test('bots fight, investigate and complete Gun Game on every map',()=>{for(let map=0;map<4;map++){const g=new Game({mode:'gun',map},{seed:718});let shots=0;for(let i=0;i<12000&&g.rules.phase!=='finished';i++){g.update(1/30);for(const e of g.events)shots+=e.type==='shot';g.events.length=0;}assert(shots>20);assert.equal(g.rules.phase,'finished',`map ${map} incomplete`);assert(g.actors.some(a=>a.gunStage===13),`map ${map} needs a blade finish`);}});
